// CRUD USERS
export const GET_USERS = "GET_USERS";
export const GET_USERS_ID = "GET_USERS_ID";
export const POST_USERS = "POST_USERS";
export const PUT_USERS = "PUT_USERS";
export const DELETE_USERS = "DELETE_USERS";
export const CREATE_USER = "CREATE_USER";
export const LOGIN_USER = "LOGIN_USER";
export const REMOVE_FAV = "REMOVE-FAV";
export const ADD_FAV = "ADD_FAV";
export const REMOVE_CART = "REMOVE-CART";
export const ADD_CART = "ADD_CART";
export const FAVS_USER = "FAVS_USER";
export const CART_USER = "CART_USER";
export const CREATE_ORDER = "CREATE_ORDER";
export const GET_ORDER = "GET_ORDER";
export const GOOGLE_AUTH = "GOOGLE_AUTH";

// CRUD SONGS
export const GET_SONGS = "GET_SONGS";
export const GET_SONGS_ID = "GET_SONGS_ID";
export const POST_SONGS = "POST_SONGS";
export const PUT_SONGS = "PUT_SONGS";
export const DELETE_SONGS = "DELETE_SONGS";
export const FILTER_SONGS = "FILTER_SONGS";

// CRUD REVIEWS
export const GET_REVIEWS = "GET_REVIEWS";
export const GET_REVIEWS_ID = "GET_REVIEWS_ID";
export const POST_REVIEWS = "POST_REVIEWS";
export const PUT_REVIEWS = "PUT_REVIEWS";
export const DELETE_REVIEWS = "DELETE_REVIEWS";

// CRUD PLAYLISTS
export const GET_PLAYLISTS = "GET_PLAYLISTS";
export const GET_PLAYLISTS_ID = "GET_PLAYLISTS_ID";
export const POST_PLAYLISTS = "POST_PLAYLISTS";
export const PUT_PLAYLISTS = "PUT_PLAYLISTS";
export const DELETE_PLAYLISTS = "DELETE_PLAYLISTS";

// CRUD ALBUMS
export const GET_ALBUMS = "GET_ALBUMS";
export const GET_ALBUMS_ID = "GET_ALBUMS_ID";
export const POST_ALBUMS = "POST_ALBUMS";
export const PUT_ALBUMS = "PUT_ALBUMS";
export const DELETE_ALBUMS = "DELETE_ALBUMS";

// CRUD MEMBERSHIPS
export const GET_MEMBERSHIPS = "GET_MEMBERSHIPS";
export const GET_MEMBERSHIPS_ID = "GET_MEMBERSHIPS_ID";
export const POST_MEMBERSHIPS = "POST_MEMBERSHIPS";
export const PUT_MEMBERSHIPS = "PUT_MEMBERSHIPS";
export const DELETE_MEMBERSHIPS = "DELETE_MEMBERSHIPS";

// GENRES
export const GET_GENRES = "GET_GENRES";
export const GET_GENRES_ID = "GET_GENRES_ID";
export const POST_GENRES = "POST_GENRES";
export const DELETE_GENRES = "DELETE_GENRES";


// STATES REDUX

export const RESET_MESSAGES = "RESET_MESSAGES";
export const RESET_USERSID_USERFAVS = "RESET_USERSID_USERFAVS";